# .github/workflows/build.yml
name: Build and Upload

on:
  push:
    branches:
      - master
  schedule:
    - cron: '0 0 * * 0'
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        pip install -r requirements.txt
        ./installResources.ps1

    - name: Build executable
      run: pyinstaller --onefile --noconsole src/main.py

    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: program-exe
        path: dist/main.exe
